name: gen_annotation
description: "A collection of lightweight Dart annotations for marking classes and members for source code generation."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.13.4
  flutter: ">=3.47.5"

dev_dependencies:
  very_good_analysis: ^11.0.0